/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieFeaturedIndexRouteImport } from './routes/movie/featured/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieFeaturedIndexRoute = MovieFeaturedIndexRouteImport.update({
  id: '/movie/featured/',
  path: '/movie/featured/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movie/featured': typeof MovieFeaturedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movie/featured': typeof MovieFeaturedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movie/featured/': typeof MovieFeaturedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movie/featured'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movie/featured'
  id: '__root__' | '/' | '/movie/featured/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovieFeaturedIndexRoute: typeof MovieFeaturedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/featured/': {
      id: '/movie/featured/'
      path: '/movie/featured'
      fullPath: '/movie/featured'
      preLoaderRoute: typeof MovieFeaturedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovieFeaturedIndexRoute: MovieFeaturedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
